language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install
  - npm start

script:
  - npm start
  - npm run to:1diary
  - npm run import